### PR TITLE
Scout

### PR DESCRIPTION
**Pull request by jerge**
Should work as intended, my thought process for scout can be seen in a comment at the bottom of scout.cs

Please come with feedback if you feel anything is weird

### CODE REVIEW

**Comment by maxarfvidssonnilsson** [comment]
The scounts can still have a fight or flight behaviour if you take "nr of enemies"/"the area of those enemies" and the same for friends. 

To increase cohesion you can do a few things: 
- create oval neighbour radious looking mostly in front of the unit. This will make them follow the units in fron of them more which in turn mean a larger group will follow the scouts. This could also be done for the scouts so that they do not see to much of the army behind them.
- Make the size of the neighbour radious dynamic dependant on the number of units inside the neighbour radious. This decreases lag when the units are tightly packed and in turn means that we can set a higher max neighbour radious increasing cohesion. 
- To disperse the scouts more we can make them avoid each other.

**Comment by maxarfvidssonnilsson** [comment]
Also, I dont know what it is but if you spawn a lot of scouts and a few enemy soldiers in different direction the scouts dont seem to know where to go. They go after one soldier for a little while and then they do a 180 and run after another soldier.

**Comment by jerge** [comment]
> Also, I dont know what it is but if you spawn a lot of scouts and a few enemy soldiers in different direction the scouts dont seem to know where to go. They go after one soldier for a little while and then they do a 180 and run after another soldier.

Well this is obviously because they want to go towards both of them and they get conflicting priorities from other behaviour (alignment/avoidance/cohesion). I don't see how they could make a consensus decision in this regards without swaying back and forth

**Comment by jerge** [comment]
> The scounts can still have a fight or flight behaviour if you take "nr of enemies"/"the area of those enemies" and the same for friends.
> 
> To increase cohesion you can do a few things:
> 
> * create oval neighbour radious looking mostly in front of the unit. This will make them follow the units in fron of them more which in turn mean a larger group will follow the scouts. This could also be done for the scouts so that they do not see to much of the army behind them.
> * Make the size of the neighbour radious dynamic dependant on the number of units inside the neighbour radious. This decreases lag when the units are tightly packed and in turn means that we can set a higher max neighbour radious increasing cohesion.
> * To disperse the scouts more we can make them avoid each other.

0. What do you mean with "The scounts can still have a fight or flight behaviour if you take "nr of enemies"/"the area of those enemies" and the same for friends."?
They have a fight or flight behaviour?!?!? Dividing it by the area of those enemies seems like it requires a bunch of complex or arbitrary calculations. If you refer to my comment regarding making them only see enemies then that will not be fixed by this since they still need to look at the "density" of friends then there's no purpose

1. We could use a capsule collider for the scouts instead but then it would be impossible for the scouts to find units that aren't in front of them, and since they don't have any behaviour to spin and scan for more units we'd simply lose the intended behaviour of the scouts (find hiding enemies/armies). If we use a capsule collider for the agents I'm pretty sure that it will be even easier for them to not see their neighbours, especially since the units tend to form a circle.

2. I'll try this

3. ?!??! yeah I know and describe that. It's still a decision for the player, not us. I already tried increasing the avoidance between scouts but that did not help

**Comment by maxarfvidssonnilsson** [comment]
> > Also, I dont know what it is but if you spawn a lot of scouts and a few enemy soldiers in different direction the scouts dont seem to know where to go. They go after one soldier for a little while and then they do a 180 and run after another soldier.
> 
> Well this is obviously because they want to go towards both of them and they get conflicting priorities from other behaviour (alignment/avoidance/cohesion). I don't see how they could make a consensus decision in this regards without swaying back and forth

Hmmm.... Maybe. But it would make more sense if they split into two groups, one for each enemy. But maybe their cohesion is to strong...

**Comment by maxarfvidssonnilsson** [comment]
> > The scounts can still have a fight or flight behaviour if you take "nr of enemies"/"the area of those enemies" and the same for friends.
> > To increase cohesion you can do a few things:
> > 
> > * create oval neighbour radious looking mostly in front of the unit. This will make them follow the units in fron of them more which in turn mean a larger group will follow the scouts. This could also be done for the scouts so that they do not see to much of the army behind them.
> > * Make the size of the neighbour radious dynamic dependant on the number of units inside the neighbour radious. This decreases lag when the units are tightly packed and in turn means that we can set a higher max neighbour radious increasing cohesion.
> > * To disperse the scouts more we can make them avoid each other.
> 
> 1. What do you mean with "The scounts can still have a fight or flight behaviour if you take "nr of enemies"/"the area of those enemies" and the same for friends."?
>    They have a fight or flight behaviour?!?!? Dividing it by the area of those enemies seems like it requires a bunch of complex or arbitrary calculations. If you refer to my comment regarding making them only see enemies then that will not be fixed by this since they still need to look at the "density" of friends and then there's no purpose
> 2. We could use a capsule collider for the scouts instead but then it would be impossible for the scouts to find units that aren't in front of them, and since they don't have any behaviour to spin and scan for more units we'd simply lose the intended behaviour of the scouts (find hiding enemies/armies). If we use a capsule collider for the agents I'm pretty sure that it will be even easier for them to not see their neighbours, especially since the units tend to form a circle.
> 3. I'll try this
> 4. ?!??! yeah I know and describe that. It's still a decision for the player, not us. I already tried increasing the avoidance between scouts but that did not help

0. Im not sure if we are on the same page. Do they already have a fight or flight behaviour? 

1. If a group can not see a enemy they tend to rotate at the lowest point forming a natural circeling behaviour. This also helps them be more decisive of what army to follow. They prefer the one in front. Since they mostly follow the units in front of them they will have more snapy reactions to changes in front. And since they can see further in front they will be less likely to be left behind. Most of the seperation is because one group is to fast leaving their friends behind.  Also im not saying they only look in front. They can still look a bit to the sides and behind. Just not as much. 

3. Okidoki.

**Pull request merged**
