### PR TITLE
Fixing spawning through ground

### PR DESCRIPTION
**Pull request by Simonolsson98**
Test if spawning on uneven ground (for example a mountain) works for you, all troops should spawn above ground!

Also test if you can drag troops around (you have to be very precise when you try to click on a troop right now, as the collider is pretty small (maybe a bigger collider just for "picking up" purposes can be added in the future). 

When dragging troops around, and for example zooming out or dragging over a mountain, there will be an offset from mouse to the troop, I will fix this later :)

### CODE REVIEW

**Comment by Simonolsson98** [comment]
forgot to mention; only works for circular spawning atm, will fix for rectangular and arrow formation aswell of course

**Comment by Simonolsson98** [comment]
I mean, either I make these 2 changes in one branch, or I make 2 branches, but at the last meeting it sounded like we didnt want to have too many branches at the same time..?

**Comment by Simonolsson98** [comment]
added spawning for rectangular and arrow aswell, test and make sure it works!

**Comment by Hoidi** [comment]
> I mean, either I make these 2 changes in one branch, or I make 2 branches, but at the last meeting it sounded like we didnt want to have too many branches at the same time..?

Standard praxis is one branch for one feature (or simliar) but eh..

**Comment by Simonolsson98** [comment]
yeah makes sense, ska tänka på det framöver

**Pull request merged**
