### PR TITLE
Economy system

### PR DESCRIPTION
**Pull request by Simonolsson98**
**PROMPTS ARE not in the exe version :(**

- Added money (50k for each player (placeholder))

- Make sure each player can spawn troops and money should decrement as intended

- When trying to spawn too many troops, prompt should appear and tell you that you can afford to spawn x more troops of this kind, allowing you to do that (by clicking ok) or cancel.

- Also added a prompt when you don't have enough money left for 1 troop of the selected sort and a prompt when you try to spawn but don't have *any* money left (0).

- should add a text that shows the cost of the spawning of the selected troop and the selected amount

### CODE REVIEW

**Comment by maxarfvidssonnilsson** [comment]
The  popup is annoying. From a design perspektive it feels like you did something wrong since a game usually do not prompt you with a pop up similar to this one. Also when you have klicked it away you have to klick on the screen to resume the game. This will result in a new popup if you dont klick on the menu.

**Comment by maxarfvidssonnilsson** [comment]
Would be nice to have the cost of the units listed beside the units. The number at the bottom can be interpreted as the cost of a single unit.

**Comment by Simonolsson98** [comment]
jag tror jag tar bort allt som har med prompts att göra, för som sagt så finns dom ändå inte när man har spelet som .exe

**Comment by Simonolsson98** [comment]
If you try to spawn more troops than you can afford, it will now just spawn the amount of troops you can afford, of this kind.

**Pull request merged**
