### PR TITLE
Castle

### PR DESCRIPTION
**Pull request by jerge**
large PR.
Solves: 
- Spawning too close to other troops
- Creates castle with prefabs (including in UI)
- Adds win condition that all your castles are dead (or all other units)
- Validates spawning location and changes map so that you only can spawn on your half of the map

### CODE REVIEW

**Comment by jerge** [comment]
Will continue with more content in another PR as to not create too huge changes at a time

**Comment by jerge** [comment]
Please check if it solves issues with VSCODE not finding the UI package

**Comment by maxarfvidssonnilsson** [comment]
Dont know how much is intentional or not so im just gonna write down everything I noticed. 

- castles can be spawned on top of mountains.

- units walks through the castles. 

- there is empty space below the castles.

- you can move on to the next stage without spawing a castle. 

- more than half the map is red making it hard to see where you can spawn units.

**Comment by jerge** [comment]
> Dont know how much is intentional or not so im just gonna write down everything I noticed.
> 
> * castles can be spawned on top of mountains.
> * units walks through the castles.
> * there is empty space below the castles.
> * you can move on to the next stage without spawing a castle.
> * more than half the map is red making it hard to see where you can spawn units.

* Will fix this in upcoming pull requests, this one started to become too large and I would prefereably avoid to make PR's that are too large to read through
* This is definitely weird, but I still think I should fix that in another PR for the same reason as above^^
* This will be fixed with the first one and addition of pillars on the edges of the prefabs
* I would like an error board before I start implementing this one, but I'll make sure I don't forget it.
* Half of the map is suppose to be red, it is intended for the red team's troops. You're only suppose to be able to spawn on your side

Thanks for your comments!

**Pull request merged**
