### PR TITLE
Minor UI fixes on score panels

### PR DESCRIPTION
**Pull request by DecibelM**
Just some really small fixes on the UI of the flocking scene:
*Team names are the same size
*Score panels made slightly smaller to fit more tightly around the text

### CODE REVIEW

**Comment by DecibelM** [comment]
And changed name from archer to Gunmen (only text, not in the code)

**Comment by DecibelM** [comment]
Do you mean in the menu scene? I can see it and I haven't changed anything in that scene for this PR. :(

**Comment by Hoidi** [comment]
Yeah in the menu. But it was the same in Jerge's PR. You can change it if you want but it's not super important

**Comment by DecibelM** [comment]
I will update the scenes in separate PRs to avoid conflicts with others, so the menu scene will be updated as well but in a different PR.

**Pull request merged**
